---
title: "Prediction"
author: "Qi Yumeng"
date: "2023-12-05"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load clean datasets

```{r libraries}
library(tidyverse)
library(tidymodels)
library(yardstick)
library(MASS)
```

```{r load_data}
df_2013_raw =  read_csv("data/merge_data_2013.csv", show_col_types = FALSE)
df_2017_raw = read_csv("data/merge_data_2017.csv", show_col_types = FALSE)

df_2013_raw = df_2013_raw |>
  mutate(if_delay = if_else(arr_delay >0,1,0),
         if_delay = factor(if_delay),
         #carrier_bin = if_else(!(carrier %in% c('UA','EV','DL','B6')),'Others',carrier),
         #month = factor(month,levels = 1:12, labels = month.abb[1:12]),
         arrival_date = paste(year,"-",month,"-",day, sep = ""),
         arrival_date = date(arrival_date)
         ) |>
  filter(!(dest %in% setdiff(unique(df_2013_raw$dest),unique(df_2017_raw$dest))),
         !(carrier %in% setdiff(unique(df_2013_raw$carrier),unique(df_2017_raw$carrier))))

df_2013_mlr = df_2013_raw |>
   dplyr::select(-`...1`,-tailnum,-if_delay,
           -year, -month, -day) 
df_2013 = df_2013_raw |>
  dplyr::select(-`...1`,-tailnum,-arr_delay,
           -year, -month, -day) 
df_2017_raw = df_2017_raw |>
  mutate(if_delay = if_else(arr_delay >0,1,0),
         if_delay = factor(if_delay),
         #carrier_bin = if_else(!(carrier %in% c('UA','EV','DL','B6')),'Others',carrier),
         #month = factor(month,levels = 1:12, labels = month.abb[1:12])
         arrival_date = paste(year,"-",month,"-",day, sep = ""),
         arrival_date = date(arrival_date))|>
  filter(!(dest %in% setdiff(unique(df_2017_raw$dest),unique(df_2013_raw$dest))),
         !(carrier %in% setdiff(unique(df_2017_raw$carrier),unique(df_2013_raw$carrier)))) 

df_2017_mlr = df_2017_raw |>
  dplyr::select(-`...1`,-tailnum,-if_delay,
           -year, -month, -day) 
df_2017 = df_2017_raw |>
    dplyr::select(-`...1`,-tailnum,-arr_delay,
           -year, -month, -day) 

# bool the target value
# bin the factor values with moderate amount of unique values
# drop some observations with too many of unique values
# there are over 100 unique values for 'dest', and each unique value accounts for around 5% or less, with a relatively even distribution,with filtering approach, we keep only the destinations that appear in both datasets and remove observations that are present in only one of the datasets.
# Convert month to factor with levels in ascending order and labels as month abbreviations
```

```{r skimr}
skimr::skim(df_2013)
skimr::skim(df_2017)
```
# construct a MLR model

```{r,fig.height=10}
fit = lm(arr_delay ~ . , data = df_2013_mlr)
stepAIC(fit, direction="both")

fit_AIC = lm(formula = arr_delay ~ origin + hour + carrier + flight + dest + 
    air_time + distance + wind_dir + pressure + visib + arrival_date, 
    data = df_2013_mlr)
summary(fit_AIC)
coeff <- tidy(fit_AIC) %>% 
  arrange(desc(abs(estimate))) %>% 
  filter(abs(estimate) > 0.5) 
ggplot(coeff, aes(x = reorder(term,estimate), y = estimate)) + geom_col() + coord_flip()+
  theme(legend.position = "none")

```

# Construct a logistic regression

## logistic
```{r}
val_set <- validation_split(df_2013, 
                            strata = if_delay, 
                            prop = 0.80)
lr_mod <- 
  logistic_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")
holidays <- c("AllSouls", "AshWednesday", "ChristmasEve", "Easter", 
              "ChristmasDay", "GoodFriday", "NewYearsDay", "PalmSunday")

lr_recipe <- 
  recipe(if_delay ~ ., data = df_2013) %>% 
  step_date(arrival_date) %>% 
  step_holiday(arrival_date, holidays = holidays) %>% 
  step_rm(arrival_date) %>% 
  step_dummy(all_nominal_predictors()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())

lr_workflow <- 
  workflow() %>% 
  add_model(lr_mod) %>% 
  add_recipe(lr_recipe)

lr_reg_grid <- tibble(penalty = 10^seq(-4, -1, length.out = 30))

lr_reg_grid %>% top_n(-5) # lowest penalty values

lr_res <- 
  lr_workflow %>% 
  tune_grid(val_set,
            grid = lr_reg_grid,
            control = control_grid(save_pred = TRUE),
            metrics = metric_set(roc_auc))

lr_plot <- 
  lr_res %>% 
  collect_metrics() %>% 
  ggplot(aes(x = penalty, y = mean)) + 
  geom_point() + 
  geom_line() + 
  ylab("Area under the ROC Curve") +
  scale_x_log10(labels = scales::label_number())

lr_plot 

top_models <-
  lr_res %>% 
  show_best("roc_auc", n = 15) %>% 
  arrange(penalty) 
top_models

# best paramters
lr_best <- 
  lr_res %>% 
  collect_metrics() %>% 
  arrange(penalty) %>% 
  slice(2)

lr_auc <- 
  lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_curve(if_delay, .pred_0) %>% 
  mutate(model = "Logistic Regression")
autoplot(lr_auc)
# calculate auc
lr_res %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_auc(if_delay, .pred_0)



# Fit the model using the optimal hyperparameters
log_reg_final <- logistic_reg(penalty = 0.000127, mixture = 1) %>%
                 set_engine("glmnet") %>%
                 set_mode("classification") %>%
                 fit(if_delay~., data = df_2013)
coeff <- tidy(log_reg_final) %>% 
  arrange(desc(abs(estimate))) %>% 
  filter(term != '(Intercept)',
         abs(estimate) > 0.1)

ggplot(coeff, aes(x = reorder(term,estimate), y = estimate, fill = term)) + geom_col() + coord_flip()+
  theme(legend.position = "none")

pred_class <- predict(log_reg_final,
                      new_data = df_2017,
                      type = "prob")
library(pROC)
roc(df_2017$if_delay, pred_class$.pred_0)$auc
roc_auc(df_2017$if_delay, as.numeric(pred_class$.pred_0))
```


## RF